# Assignment 02 For Numpy Solution by _PIAIC_167010

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [1]:
import numpy as np
array = np.arange(10).reshape(2,5)
array

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [2]:
#using the function vstack with array names as an argument
array = np.arange(10).reshape(2,5)
ones = np.ones(10, dtype = int).reshape(2,5)
vert_stacked_array = np.vstack((array, ones))
vert_stacked_array

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [3]:
#using the function hstack with array names as an argument
array = np.arange(10).reshape(2,5)
ones = np.ones(10, dtype = int).reshape(2,5)
hori_stacked_array = np.hstack((array, ones))
hori_stacked_array

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [4]:
#using the function flatten with the array name and no arguments
array = array.flatten()
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [5]:
high_dim_arr = np.arange(15).reshape(1,5,3)
high_dim_arr = high_dim_arr.flatten()
high_dim_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [6]:
high_dim_arr = high_dim_arr.reshape(1,5,3)
high_dim_arr

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [7]:
arr_5X5 = np.arange(25).reshape(5,5)
np.square(arr_5X5)

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576]], dtype=int32)

## Question:8

### Create 5x6 an array and find the mean?

In [8]:
arr_5X6 = np.arange(30).reshape(5,6)
arr_5X6.mean()

14.5

## Question:9

### Find the standard deviation of the previous array in Q8?

In [9]:
arr_5X6.std()

8.65544144839919

## Question:10

### Find the median of the previous array in Q8?

In [10]:
np.median(arr_5X6)

14.5

## Question:11

### Find the transpose of the previous array in Q8?

In [11]:
arr_5X6.T

array([[ 0,  6, 12, 18, 24],
       [ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [12]:
arr_4x4 = np.arange(16).reshape(4,4) #4x4 array creation
np.sum(np.diagonal(arr_4x4)) #sum of the diagonal

30

## Question:13

### Find the determinant of the previous array in Q12?

In [13]:
np.linalg.det(arr_4x4)

0.0

## Question:14

### Find the 5th and 95th percentile of an array?

In [14]:
lin_arr = arr_4x4.flatten()
fifth = np.percentile(lin_arr,5)
ninety_fifth = np.percentile(lin_arr,95)
print(fifth, 
ninety_fifth)

0.75 14.25


## Question:15

### How to find if a given array has any null values?

In [15]:
np.isnan(lin_arr)

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False])