# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [1]:
import numpy as np

2. Create a null vector of size 10 

In [2]:
null_vec = np.zeros(10)

3. Create a vector with values ranging from 10 to 49

In [3]:
vec = np.arange(10,49)

4. Find the shape of previous array in question 3

In [4]:
vec_shape = vec.shape

5. Print the type of the previous array in question 3

In [5]:
print(type(vec))

<class 'numpy.ndarray'>


6. Print the numpy version and the configuration


In [6]:
print(np.__version__)
print(np.show_config())

1.18.1
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/ProgramData/Anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\

7. Print the dimension of the array in question 3


In [7]:
print("Dimension of array in Question 03 is: ", vec.ndim)

Dimension of array in Question 03 is:  1


8. Create a boolean array with all the True values

In [8]:
bool_arr = np. ones(10, dtype=bool)

9. Create a two dimensional array




In [9]:
arr_2D = np.ones((4,4))

10. Create a three dimensional array



In [10]:
arr_3D = np.ones((4,4,4))

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [11]:
reverse_arr = vec[::-1]

12. Create a null vector of size 10 but the fifth value which is 1 

In [12]:
null_vec = np.zeros(10)
null_vec[4] = 1

13. Create a 3x3 identity matrix

In [13]:
identity_matrix = np.identity(3)

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [14]:
arr = np.array([1, 2, 3, 4, 5])
float_arr = np.asfarray(arr)

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [15]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],

           [7., 2., 12.]])
mul_arr = np.multiply(arr1, arr2)

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [16]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.],

            [7., 2., 12.]])
comparison = arr1 == arr2

17. Extract all odd numbers from arr with values(0-9)

In [17]:
arr = np.arange(0,9)
odd_arr = arr[arr % 2 != 0]

18. Replace all odd numbers to -1 from previous array

In [18]:
minus_1_arr = np.place(odd_arr, odd_arr % 2 != 0, -1)

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [19]:
arr = np.arange(10)
arr[5:9] = 12

20. Create a 2d array with 1 on the border and 0 inside

In [20]:
arr_2d = np.ones((5,5))
border_inside_arr = arr_2d[1:-1,1:-1] = 0

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [21]:
arr2d = np.array([[1, 2, 3],

            [4, 5, 6], 

            [7, 8, 9]])
np.place(arr2d, arr2d == 5, 12)

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [22]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0,:,:] = 64

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [23]:
arr2d = np.arange(0,9).reshape(3,3)
sliced_1D_arr = arr2d[0]

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [24]:
arr2d = np.arange(0,9).reshape(3,3)
sliced_2nd_1D_arr = arr2d[1][1]

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [25]:
arr2d = np.arange(0,9).reshape(3,3)
sliced_3rd_1st_two_arr = arr2d[0:2,-1:]

26. Create a 10x10 array with random values and find the minimum and maximum values

In [26]:
ran_arr = np.random.random((10,10))
ran_arr_min, ran_arr_max = ran_arr.min(), ran_arr.max()

27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [27]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.intersect1d(a, b))

[2 4]


28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [28]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.where(a==b))

(array([1, 3, 5, 7], dtype=int64),)


29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [29]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
print(data[names!='Will'])

[[ 1.01345495  0.88681604  0.81521587  0.00520517]
 [-0.55778532 -3.04856541 -1.0905734  -0.55694686]
 [ 0.99059219  0.96994846 -2.32849365  0.13351852]
 [ 0.21527039 -0.76634504 -0.40680976  1.50604751]
 [-0.29750741 -1.27084392  1.1819033  -1.21997832]]


30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [30]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
print(data[names =='Bob'])

[[-0.70898353 -1.14081144  1.15137387 -0.32727923]
 [ 2.87323248 -0.36941909 -0.18377051  0.11716567]]


Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [31]:
arr_2D = np.arange(1,16).reshape(5,3)

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [32]:
arr_2D = np.arange(1,17).reshape(2,2,4)

33. Swap axes of the array you created in Question 32

In [33]:
swap_axes = np.swapaxes(arr_2D,0,1)

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [34]:
arr = np.random.uniform(0.1,2,10)
arr = np.sqrt(arr)
arr = np.where(arr<0.5, 0, arr)

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [35]:
arr1 = np.random.randint(1, 100, 12)
arr2 = np.random.randint(1, 100, 12)
max_arr = np.where(arr1>arr2, arr1, arr2)

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [36]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names = sorted(set(names))

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [37]:
a = np.array([1,2,3,4,5]) 
b = np.array([5,6,7,8,9])
removed_from_a = np.setdiff1d(a, b)

38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [38]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = np.array([[10,10,10]])
sampleArray = np.delete(sampleArray , 1, axis =1)
sampleArray = np.insert(sampleArray , 1, newColumn, axis = 1) 

39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [39]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
z = np.dot(x,y)

40. Generate a matrix of 20 random values and find its cumulative sum

In [40]:
a = np.arange(20).reshape(5,4)
cum_sum = np.cumsum(a)